/** Generated by YAKINDU Statechart Tools code generator. */
package ca.mcgill.ecse223.kingdomino.statemachine.gameplay;

import ca.mcgill.ecse223.kingdomino.statemachine.IStatemachine;

public interface IGameplayStatemachine extends IStatemachine {
	public interface SCIGame {
	
		public void setSCIGameOperationCallback(SCIGameOperationCallback operationCallback);
	
	}
	
	public interface SCIGameOperationCallback {
	
		public void create();
		
		public void end();
		
	}
	
	public SCIGame getSCIGame();
	
	public interface SCIDraft {
	
		public void raiseReady();
		
		public void raiseValidSelection();
		
		public void setSCIDraftOperationCallback(SCIDraftOperationCallback operationCallback);
	
	}
	
	public interface SCIDraftOperationCallback {
	
		public void prepareFirst();
		
		public void prepareNext();
		
		public void revealFirst();
		
		public void revealNext();
		
	}
	
	public SCIDraft getSCIDraft();
	
	public interface SCITurn {
	
		public void raiseNext();
		
		public void raisePreplaceDomino();
		
		public void raiseValidPlacement();
		
		public void setSCITurnOperationCallback(SCITurnOperationCallback operationCallback);
	
	}
	
	public interface SCITurnOperationCallback {
	
		public void prepare();
		
		public boolean isLast();
		
	}
	
	public SCITurn getSCITurn();
	
	public interface SCIPlayer {
	
		public void raiseDiscard();
		
		public void setSCIPlayerOperationCallback(SCIPlayerOperationCallback operationCallback);
	
	}
	
	public interface SCIPlayerOperationCallback {
	
		public boolean isLast();
		
		public void setToFirst();
		
		public void setNext();
		
		public boolean checkDiscard();
		
	}
	
	public SCIPlayer getSCIPlayer();
	
}
